Django/Django/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^riddles/', include('riddles.urls')),
    path('admin/', admin.site.urls),
]

Django/riddles/models.py
from django.db import models
# встроенная модель пользователя
# нужна для авторов сообщений
from django.contrib.auth.models import User
# тип "временнАя зона" для получения текущего времени
from django.utils import timezone

class Riddle(models.Model):
    riddle_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')


class Option(models.Model):
    riddle = models.ForeignKey(Riddle, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)


class Message(models.Model):
    chat = models.ForeignKey(
        Riddle,
        verbose_name='Чат под загадкой',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    message = models.TextField('Сообщение')
    pub_date = models.DateTimeField(
        'Дата сообщения',
        default=timezone.now)


class Mark(models.Model):
    riddle = models.ForeignKey(
        Riddle,
        verbose_name='Загадка',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    mark = models.IntegerField(
        verbose_name='Оценка')
    pub_date = models.DateTimeField(
        'Дата оценки',
        default=timezone.now)

Django/templates/admin.html
{% extends 'base.html' %}
{% block main %}
    {% if user.is_staff %}
        {% if message %}
            <p class="alert alert-success">
                <strong>{{ message }}</strong>
            </p>
        {% endif %}
        <div class="card mb-3">
        <div class="card-body">
        <form action="../post_riddle/" method="post">
            {% csrf_token %}
            <h5>Add riddle:</h5>
            <div class="mb-3">
                <input class="form-control"
                       placeholder="Riddle text"
                       name="text"
                       required/>
            </div>
            <div class="card mb-3">
            <div class="card-body" id="options_new">
                <div class="mb-3">
                    <input class="form-control"
                           placeholder="Option 1 (correct)"
                           name="option1"
                           required/>
                </div>
                <div class="mb-3">
                    <input class="form-control"
                           placeholder="Option 2"
                           name="option2"
                           required/>
                </div>
                <script>
                    var option_counter = 2;
                </script>
            </div>
            </div>
            <div class="mb-3">
                <button class="btn btn-success"
                        onclick="addOption('options_new', 0)"
                        type="button">
                    + Add option
                </button>
                <button class="btn btn-success">
                    Save
                </button>
            </div>
            <input type="hidden"
                   name="riddle_id"
                   value="0"/>
        </form>
        </div>
        </div>
        <div class="card mb-3">
        <div class="card-body">
        <h4 class="card-title">Available Riddles</h4>
        {% if latest_riddles %}
            <ul>
                {% for riddle in latest_riddles %}
                    <li>
                        <a href="/riddles/{{ riddle.id }}/">
                            {{ riddle.riddle_text }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No riddles are available right now.</p>
        {% endif %}
        </div>
        </div>

        <script>
        //добавление блока для нового ответа
        function addOption(target, pos_in_array){
            var option=document.createElement("div");
            option_counter += 1;
            option.className="input-group mb-3";
            option.innerHTML=
                '<input class="form-control"' +
                '       placeholder="Option ' + 
                        option_counter + '"' + 
                '       name="option' + option_counter + '"/>' +
                '<div class="input-group-append">' +
                '     <button class="btn btn-danger"' +
                '             type="button"' +
                '             onclick="removeParent(' +
                '               this.parentNode)">' +
                '          Delete' +
                '     </button>' +
                '</div>';
            document.getElementById(target).appendChild(option);
        }
        //удаление блока ответа с поправкой номеров других ответов
        function removeParent(child){
            var optionList=child.parentNode.parentNode;
            var currentOption=child.parentNode;
            optionList.removeChild(currentOption);
            for(var i=3; i<optionList.children.length; i+=1){
                var opt=optionList.children[i].children[0];
                opt.name="option"+(i);
                opt.placeholder="Option "+(i);
            }
            option_counter -= 1;
        }
        </script>
    {% else %}
        <h4>Access denied.</h4>
    {% endif %}
{% endblock %}

Django/templates/answer.html
{% extends 'base.html' %}
{% block main %}
<h4 class="card-title">{{ riddle.riddle_text }}</h4>
{% if error_message %}
    <p class="alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}
<form action="answer/" method="post">
    {% csrf_token %}
    {% for option in riddle.option_set.all %}
        <input type="radio" name="option"
            id="option{{ forloop.counter }}"
            value="{{ option.id }}"/>
        <label for="option{{ forloop.counter }}">
            {{ option.text }}
        </label><br>
    {% endfor %}
    <input type="submit" value="Answer"/>
</form>
<hr>
<h4>Rating</h4>
    <p>Average rating:
        <span id="avg_mark_span">
            {{ avg_mark }}
        </span>
    </p>
{% if user.is_authenticated %}
    {% if already_rated_by_user == 0%}
        <form action="post_mark/" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="1"/> 1
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="2"/> 2
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="3"/> 3
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="4"/> 4
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="5"/> 5
                </div>
                <div class="col-sm text-center">
                    <input class="btn btn-success"
                        type="submit"
                        value="Send mark"/>
                </div>
            </div>
        </form>
        {% else %}
        Your rating: {{ user_rating }}
    {% endif %}

{% endif %}

<hr>
<h4>Chat</h4>
{% if user.is_authenticated %}
    <form action="post/" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input type="text"
             class="form-control"
             placeholder="Your message"
             name="message"/>
      <div class="input-group-append">
        <input class="btn btn-success"
                type="submit"
                value="Send"/>
      </div>
    </div>
</form>
{% endif %}
<div id="history">
    {% for message in latest_messages %}
        <div class="card">
        <div class="card-body">
            <strong>
                {{ message.author.username }}
            </strong>
            <br/>
            <em>
                {{ message.pub_date|date:'Y-m-d H:i:s' }}
            </em>
            <br/>
            {{ message.message }}
        </div>
        </div>
        <br/>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>
<script>
function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
}
function parse_msg_update_response(data, success){
    //alert(data);
    res = JSON.parse(data);
    res_str = "";
    for(i=0;i<res.length;i++){
        // HTML-код вставляемых блоков с сообщениями
        // скопирован выше - тот, что выводится
        // при загрузке страницы
        res_str += '<div class="card">\n' +
            '        <div class="card-body">\n' +
            '            <strong>\n' +
            '                '+res[i].author__username+'\n' +
            '            </strong>\n' +
            '            <br/>\n' +
            '            <em>\n' +
            '                '+res[i].pub_date+'\n' +
            '            </em>\n' +
            '            <br/>\n' +
            '            '+res[i].message+'\n' +
            '        </div>\n' +
            '        </div>\n' +
            '        <br/>'
    }
    $("#history").html(res_str);
}
setInterval(send_msg_update_request, 3000);
</script>
<script>
function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
    $.get("get_mark/",{},parse_mark_update_response);
}
//старая функция
function parse_msg_update_response(data, success){
...
}
function parse_mark_update_response(data, success){
    res = JSON.parse(data);
    $("#avg_mark_span").html(res["mark__avg"].toFixed(1));
}
setInterval(send_msg_update_request, 1000);
</script>

{% endblock %}

Django/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>Riddles</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Riddles</h1>
            {% if user.is_authenticated %}
                <p class="text-right">
                    Hello, {{ user.username }}!
                    <a href="/riddles/logout">Log out</a> |
                    <a href="/riddles/password-change">Change password</a>
                    {% if user.is_staff %}
                        | <a href="/riddles/admin">Admin panel</a>
                    {% endif %}
                    {% if user.email == '' %}
                        | <a href="/riddles/subscribe">Subscribe</a>
                    {% else %}
                        | <a href="/riddles/unsubscribe">Unsubscribe</a>
                    {% endif %}
                </p>

            {% else %}
                <p class="text-right">
                    <a href="/riddles/login">Log in</a> |
                    <a href="/riddles/register">Register</a>
                </p>
            {% endif %}
            <hr class="mt-0 mb-4">
            <div class="card">
                <div class="card-body">
                    {% block main %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Django/templates/index.html
{% extends 'base.html' %}
{% block main %}
    <h4 class="card-title">Available Riddles</h4>
    {% if message %}
        <p class="alert alert-success">
            <strong>{{ message }}</strong>
        </p>
    {% endif %}
    {% if latest_riddles %}
        <ul>
            {% for riddle in latest_riddles %}
                <li>
                    <a href="/riddles/{{ riddle.id }}/">
                        {{ riddle.riddle_text }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No riddles are available right now.</p>
    {% endif %}
{% endblock %}

Django/templates/subscribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit"
            class="btn btn-success btn-block">
            Subscribe</button>
        <a href=".." class="btn btn-danger btn-block">
            Back to home
        </a>
    </form>
{% endblock %}